# Even Fibonacci numbers
   
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

fibo_1 = 0
fibo_2 = 1
sum_even = fibo_1
fibo = 0
while fibo < 4000000:
	fibo = fibo_1 + fibo_2
	fibo_1 = fibo_2
	fibo_2 = fibo
	if fibo % 2 == 0:
		sum_even = sum_even + fibo

print(sum_even)